### ISSUE TITLE
TwoClickHandler: Wrong extender declarations

### ISSUE THREAD

**Issue by fernewelten** [adventuregamestudio/ags-templates#1]
Line 4 of `TwoClickHandler.asc` has:
```
void set_ActionLabel(this TwoClickHandler*,  Label* label)
{ ...
```

In my opinion, that's wrong although the (old) compiler will tolerate it. Because the relevant declaration in `TwoClickHandler.ash`, line 48 is:
```
struct TwoClickHandler {
  import static attribute Label* ActionLabel;
...
```
(Note the `static` keyword)

The correct declaration would be, 
```
void set_ActionLabel(static TwoClickHandler,  Label* label)
{ ...
```

I've tested that version of the declaration, and the (old) compiler groks it, too. 

The new compiler will currently only grok the second version.

Similar issues for:
Line 10, `get_ActionLabel`
Line 18, `set_InventoryGUI`
Line 23, `get_InventoryGUI`
Line 31, `set_ReversedClicks`
Line 36, `get_ReversedClicks`
Line 52, `set_PopupDistance`
Line 57, `get_PopupDistance`
Line 65, `set_PopupProportional`
Line 70, `get_PopupProportional`

**Comment by ivan-mogilko** [comment]
@fernewelten this ticket should be opened in template-source instead:
https://github.com/adventuregamestudio/ags-template-source

**Comment by fernewelten** [comment]
Moved to https://github.com/adventuregamestudio/ags-template-source/issues/26
